### ISSUE TITLE
您好，我想请问有关FINN框架的问题

### ISSUE THREAD

**Issue by TATynise** [KokyoK/wechat-program#1]
之前我看到您在FINN的讨论区提出了有关残差结构无法转换成HLS的问题，我也遇到了同样的问题，我尝试了各种函数还是失败了。请问您解决了该问题吗？您是如何解决的呢？

**Comment by KokyoK** [comment]
没解决，残差结构要转换需要改很多setting。我最后网络直接舍弃残差结构，多加了其他的层。Futher discussion: Wechat: XHHEEOvO
